[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name                 = "ai-image-renamer"
version              = "0.1.0"
description          = "Rename images based on AI tags"
readme               = "README.md"
requires-python      = ">=3.8"
dependencies         = []

[project.scripts]
image-renamer = "ai_image_renamer.cli:main"
